import {hsvToRgb,rgbHex} from './color-picker.js';

function bytesToBase64Url(bytes){let s='';for(let i=0;i<bytes.length;i++)s+=String.fromCharCode(bytes[i]);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function base64UrlToBytes(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const raw=atob(s),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
function xorshift32(seed){let x=(seed|0)||0x6d2b79f5;return ()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return (x>>>0)/4294967296;};}
function range(rng,a,b){return a+rng()*(b-a);}
function int(rng,a,b){return Math.floor(range(rng,a,b+1));}

export class SeedManager {
  constructor(state,view,ui,renderer,colorPicker,mobiusPicker){this.state=state;this.view=view;this.ui=ui;this.renderer=renderer;this.colorPicker=colorPicker;this.mobiusPicker=mobiusPicker;this.browserSeed=1;this.mode='browser';this.seedEditing=false;this.failed=null;this.replayToken=0;this.seedTimer=null;this.liveLoadTimer=null;this.suppressWrite=false;this.bind();this.setMode('browser',false);}
  status(label,color){this.ui.seedState.textContent=label;this.ui.seedState.style.color=color;}
  drawingState(){const s=this.state;return {v:1,sx:+s.colorX.toFixed(4),sy:+s.colorY.toFixed(4),b:+s.hBrush.toFixed(4),o:+s.alpha.toFixed(3),n:s.sliceCount,g:s.showGrid,ma:[+this.view.pickerA.x.toFixed(6),+this.view.pickerA.y.toFixed(6)],m:this.view.transforms.map(a=>[+a.x.toFixed(6),+a.y.toFixed(6)]),s:s.strokes.map(st=>({c:st.color,a:+st.alpha.toFixed(3),r:+st.radius.toFixed(4),p:st.points.map(p=>[+p.x.toFixed(5),+p.y.toFixed(5)])}))};}
  encodeFreehand(){return 'HYP1-'+bytesToBase64Url(new TextEncoder().encode(JSON.stringify(this.drawingState())));}
  parseFreehand(raw){raw=raw.trim();if(!raw.startsWith('HYP1-'))throw new Error('Drawing code must begin HYP1-');const st=JSON.parse(new TextDecoder().decode(base64UrlToBytes(raw.slice(5))));if(st.v!==1)throw new Error('Unsupported drawing code version');return st;}
  hydrate(st){return {colorX:Math.max(0,Math.min(1,Number(st.sx)||0)),colorY:Math.max(0,Math.min(1,Number(st.sy)||0)),hBrush:Math.max(.03,Math.min(.8,Number(st.b)||.22)),alpha:Math.max(.1,Math.min(1,Number(st.o)||.9)),sliceCount:Math.max(2,Math.min(24,Math.round(Number(st.n)||8))),showGrid:st.g!==false,pickerMobiusA:Array.isArray(st.ma)?{x:Number(st.ma[0])||0,y:Number(st.ma[1])||0}:{x:0,y:0},viewTransforms:Array.isArray(st.m)?st.m.map(a=>({x:Number(a[0])||0,y:Number(a[1])||0})):[],strokes:Array.isArray(st.s)?st.s.map(x=>({color:x.c||'#ff5c8a',alpha:Number(x.a)||.9,radius:Number(x.r)||.22,points:Array.isArray(x.p)?x.p.map(p=>({x:Number(p[0])||0,y:Number(p[1])||0})):[]})):[]};}
  generated(seed){const rng=xorshift32(seed|0),generated=[],count=int(rng,4,14);for(let s=0;s<count;s++){const points=[],pc=int(rng,12,48);let ang=range(rng,0,Math.PI*2),rad=range(rng,.08,.82),curl=range(rng,-.18,.18);for(let i=0;i<pc;i++){curl=Math.max(-.28,Math.min(.28,curl+range(rng,-.025,.025)));ang+=curl+range(rng,-.09,.09);rad=Math.max(.025,Math.min(.94,rad+range(rng,-.045,.045)));points.push({x:rad*Math.cos(ang),y:rad*Math.sin(ang)});}generated.push({color:rgbHex(hsvToRgb(rng(),range(rng,.65,1),range(rng,.55,1))),alpha:range(rng,.5,1),radius:range(rng,.045,.24),points});}const a=range(rng,0,Math.PI*2),rr=Math.sqrt(rng())*.72;return {colorX:rng(),colorY:rng()*.5,hBrush:range(rng,.08,.32),alpha:range(rng,.6,1),sliceCount:int(rng,3,18),showGrid:rng()>.35,pickerMobiusA:{x:rr*Math.cos(a),y:rr*Math.sin(a)},viewTransforms:[],strokes:generated};}
  applySettings(h){Object.assign(this.state,{colorX:h.colorX,colorY:h.colorY,hBrush:h.hBrush,alpha:h.alpha,sliceCount:h.sliceCount,showGrid:h.showGrid});this.view.pickerA=h.pickerMobiusA||{x:0,y:0};this.view.transforms=(h.viewTransforms||[]).map(a=>({...a}));this.ui.brush.value=this.state.hBrush;this.ui.alpha.value=this.state.alpha;this.ui.slices.value=this.state.sliceCount;this.ui.br.textContent=this.state.hBrush.toFixed(2);this.ui.sliceReadout.textContent=this.state.sliceCount;this.ui.grid.textContent=this.state.showGrid?'Hide grid':'Show grid';this.colorPicker.sync();this.mobiusPicker.draw();}
  replay(h){this.suppressWrite=true;this.applySettings(h);this.state.strokes=[];this.state.currentStroke=null;this.renderer.redraw();const queue=[];for(const s of h.strokes){const partial={color:s.color,alpha:s.alpha,radius:s.radius,points:[]};queue.push(['start',partial]);for(const p of s.points)queue.push(['point',partial,p]);queue.push(['finish',partial]);}const token=++this.replayToken,per=Math.max(1,Math.ceil(queue.length/220));let i=0;this.status('drawing','#79c0ff');const step=()=>{if(token!==this.replayToken){this.suppressWrite=false;return;}let n=0;while(i<queue.length&&n<per){const [type,stroke,p]=queue[i++];if(type==='start')this.state.currentStroke=stroke;else if(type==='point')stroke.points.push({...p});else {this.state.strokes.push(stroke);this.state.currentStroke=null;}n++;}this.renderer.redraw();if(i<queue.length)requestAnimationFrame(step);else {this.state.currentStroke=null;this.suppressWrite=false;this.status('loaded','#7ee787');if(this.mode==='freehand'&&!this.seedEditing)this.updateVisible(true);}};requestAnimationFrame(step);}
  loadBrowser(raw){const s=raw.trim();if(!/^\d+$/.test(s))throw new Error('Seed must be an integer');const n=Number(s);if(!Number.isSafeInteger(n)||n<0||n>2147483647)throw new Error('Seed must be 0–2147483647');this.browserSeed=n;this.replay(this.generated(n));}
  loadFreehand(raw){this.replay(this.hydrate(this.parseFreehand(raw)));}
  currentCode(){if(this.mode==='freehand'){this.seedEditing=false;this.updateVisible(true);}return this.ui.seedInput.value;}
  updateVisible(force=false){if(this.suppressWrite||(this.seedEditing&&!force))return;this.ui.seedInput.value=this.mode==='browser'?String(this.browserSeed):this.encodeFreehand();this.status('ready','#8fa0b8');}
  scheduleUpdate(){if(this.mode!=='freehand')return;clearTimeout(this.seedTimer);this.seedTimer=setTimeout(()=>this.updateVisible(false),40);}
  attempt(){const raw=this.ui.seedInput.value,key=this.mode+'|'+raw;if(this.failed===key)return false;try{this.mode==='browser'?this.loadBrowser(raw):this.loadFreehand(raw);this.failed=null;return true;}catch{this.failed=key;this.status('fail','#ff6b6b');return false;}}
  setMode(mode,confirmErase=true){if(confirmErase&&this.mode==='freehand'&&mode==='browser'){if(!window.confirm('Switch to Seed Browser? This will erase your freehand illustration.')){this.ui.seedMode.value='freehand';return;}}this.mode=mode;this.ui.seedMode.value=mode;this.seedEditing=false;this.failed=null;this.replayToken++;const browser=mode==='browser';this.ui.prevSeed.style.display=browser?'':'none';this.ui.nextSeed.style.display=browser?'':'none';this.ui.randomSeed.style.display=browser?'':'none';this.ui.seedInput.placeholder=browser?'Numeric seed':'HYP1 drawing code';this.updateVisible(true);if(browser)this.replay(this.generated(this.browserSeed));}
  markFreehand(){if(this.mode==='browser'){this.mode='freehand';this.ui.seedMode.value='freehand';this.ui.prevSeed.style.display='none';this.ui.nextSeed.style.display='none';this.ui.randomSeed.style.display='none';this.ui.seedInput.placeholder='HYP1 drawing code';this.seedEditing=false;}}
  bind(){const u=this.ui;u.seedMode.addEventListener('change',()=>this.setMode(u.seedMode.value,true));u.prevSeed.onclick=()=>{if(this.mode!=='browser')return;this.browserSeed=Math.max(0,this.browserSeed-1);this.seedEditing=false;this.updateVisible(true);this.replay(this.generated(this.browserSeed));};u.nextSeed.onclick=()=>{if(this.mode!=='browser')return;this.browserSeed=Math.min(2147483647,this.browserSeed+1);this.seedEditing=false;this.updateVisible(true);this.replay(this.generated(this.browserSeed));};u.randomSeed.onclick=()=>{if(this.mode!=='browser')return;this.browserSeed=Math.floor(Math.random()*2147483648);this.seedEditing=false;this.updateVisible(true);this.replay(this.generated(this.browserSeed));};u.copySeed.onclick=async()=>{this.updateVisible(true);try{await navigator.clipboard.writeText(u.seedInput.value);const old=u.copySeed.textContent;u.copySeed.textContent='Copied';setTimeout(()=>u.copySeed.textContent=old,900);}catch{u.seedInput.select();document.execCommand('copy');}};u.loadSeed.onclick=()=>{this.seedEditing=false;this.failed=null;this.attempt();};u.seedInput.addEventListener('focus',()=>this.seedEditing=true);u.seedInput.addEventListener('blur',()=>this.seedEditing=false);u.seedInput.addEventListener('input',()=>{this.seedEditing=true;this.failed=null;this.replayToken++;this.status('editing','#f0b45c');clearTimeout(this.liveLoadTimer);this.liveLoadTimer=setTimeout(()=>this.attempt(),110);});u.seedInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();this.seedEditing=false;this.failed=null;this.attempt();}});}
}
